export const BUTTONS_DATA = [
  { key: '`', ruKey: 'ё', code: 'Backquote' },
  { key: '1', ruKey: '1', code: 'Digit1' },
  { key: '2', ruKey: '2', code: 'Digit2' },
  { key: '3', ruKey: '3', code: 'Digit3' },
  { key: '4', ruKey: '4', code: 'Digit4' },
  { key: '5', ruKey: '5', code: 'Digit5' },
  { key: '6', ruKey: '6', code: 'Digit6' },
  { key: '7', ruKey: '7', code: 'Digit7' },
  { key: '8', ruKey: '8', code: 'Digit8' },
  { key: '9', ruKey: '9', code: 'Digit9' },
  { key: '0', ruKey: '0', code: 'Digit0' },
  { key: '-', ruKey: '-', code: 'Minus' },
  { key: '=', ruKey: '=', code: 'Equal' },
  { key: 'Backspace', code: 'Backspace' },
  { key: 'Tab', code: 'Tab' },
  { key: 'q', ruKey: 'й', code: 'KeyQ' },
  { key: 'w', ruKey: 'ц', code: 'KeyW' },
  { key: 'e', ruKey: 'у', code: 'KeyE' },
  { key: 'r', ruKey: 'к', code: 'KeyR' },
  { key: 't', ruKey: 'е', code: 'KeyT' },
  { key: 'y', ruKey: 'н', code: 'KeyY' },
  { key: 'u', ruKey: 'г', code: 'KeyU' },
  { key: 'i', ruKey: 'ш', code: 'KeyI' },
  { key: 'o', ruKey: 'щ', code: 'KeyO' },
  { key: 'p', ruKey: 'з', code: 'KeyP' },
  { key: '[', ruKey: 'х', code: 'BracketLeft' },
  { key: ']', ruKey: 'ъ', code: 'BracketRight' },
  { key: '\\', ruKey: '\\', code: 'Backslash' },
  { key: 'Delete', code: 'Delete' },
  { key: 'CapsLock', code: 'CapsLock' },
  { key: 'a', ruKey: 'ф', code: 'KeyA' },
  { key: 's', ruKey: 'ы', code: 'KeyS' },
  { key: 'd', ruKey: 'в', code: 'KeyD' },
  { key: 'f', ruKey: 'а', code: 'KeyF' },
  { key: 'g', ruKey: 'п', code: 'KeyG' },
  { key: 'h', ruKey: 'р', code: 'KeyH' },
  { key: 'j', ruKey: 'о', code: 'KeyJ' },
  { key: 'k', ruKey: 'л', code: 'KeyK' },
  { key: 'l', ruKey: 'д', code: 'KeyL' },
  { key: ';', ruKey: 'ж', code: 'Semicolon' },
  { key: "'", ruKey: 'э', code: 'Quote' },
  { key: 'Enter', code: 'Enter' },
  { key: 'Shift', code: 'ShiftLeft' },
  { key: 'z', ruKey: 'я', code: 'KeyZ' },
  { key: 'x', ruKey: 'ч', code: 'KeyX' },
  { key: 'c', ruKey: 'с', code: 'KeyC' },
  { key: 'v', ruKey: 'м', code: 'KeyV' },
  { key: 'b', ruKey: 'и', code: 'KeyB' },
  { key: 'n', ruKey: 'т', code: 'KeyN' },
  { key: 'm', ruKey: 'ь', code: 'KeyM' },
  { key: ',', ruKey: 'б', code: 'Comma' },
  { key: '.', ruKey: 'ю', code: 'Period' },
  { key: '/', ruKey: '.', code: 'Slash' },
  { key: 'ArrowUp', code: 'ArrowUp' },
  { key: 'Shift', code: 'ShiftRight' },
  { key: 'Control', code: 'ControlLeft' },
  { key: 'Meta', code: 'MetaLeft' },
  { key: 'Alt', code: 'AltLeft' },
  { key: ' ', code: 'Space' },
  { key: 'Alt', code: 'AltRight' },
  { key: 'ArrowLeft', code: 'ArrowLeft' },
  { key: 'ArrowDown', code: 'ArrowDown' },
  { key: 'ArrowRight', code: 'ArrowRight' },
  { key: 'Control', code: 'ControlRight' },
];

// [en, ru, caps en, caps ru]
export const BTNS_DATA = {
  Backquote: ['`', 'ё', '~', 'Ё'],
  Digit1: ['1', '1', '!', '!'],
  Digit2: ['2', '2', '@', '"'],
  Digit3: ['3', '3', '#', '№'],
  Digit4: ['4', '4', '$', ';'],
  Digit5: ['5', '5', '%', '%'],
  Digit6: ['6', '6', '^', ':'],
  Digit7: ['7', '7', '&', '?'],
  Digit8: ['8', '8', '*', '*'],
  Digit9: ['9', '9', '(', '('],
  Digit0: ['0', '0', ')', ')'],
  Minus: ['-', '-', '-', '-'],
  Equal: ['=', '=', '=', '='],
  KeyQ: ['q', 'й', 'Q', 'Й'],
  KeyW: ['w', 'ц', 'W', 'Ц'],
  KeyE: ['e', 'у', 'E', 'У'],
  KeyR: ['r', 'к', 'R', 'К'],
  KeyT: ['t', 'е', 'T', 'Е'],
  KeyY: ['y', 'н', 'Y', 'Н'],
  KeyU: ['u', 'г', 'U', 'Г'],
  KeyI: ['i', 'ш', 'I', 'Ш'],
  KeyO: ['o', 'щ', 'O', 'Щ'],
  KeyP: ['p', 'з', 'P', 'З'],
  BracketLeft: ['[', 'х', '{', 'Х'],
  BracketRight: [']', 'ъ', '}', 'Ъ'],
  Backslash: ['\\', '\\', '|', '/'],
  KeyA: ['a', 'ф', 'A', 'Ф'],
  KeyS: ['s', 'ы', 'S', 'Ы'],
  KeyD: ['d', 'в', 'D', 'В'],
  KeyF: ['f', 'а', 'F', 'А'],
  KeyG: ['g', 'п', 'G', 'П'],
  KeyH: ['h', 'р', 'H', 'Р'],
  KeyJ: ['j', 'о', 'J', 'О'],
  KeyK: ['k', 'л', 'K', 'Л'],
  KeyL: ['l', 'д', 'L', 'Д'],
  Semicolon: [';', 'ж', ':', 'Ж'],
  Quote: ["'", 'э', '"', 'Э'],
  KeyZ: ['z', 'я', 'Z', 'Я'],
  KeyX: ['x', 'ч', 'X', 'Ч'],
  KeyC: ['c', 'с', 'C', 'С'],
  KeyV: ['v', 'м', 'V', 'М'],
  KeyB: ['b', 'и', 'B', 'И'],
  KeyN: ['n', 'т', 'N', 'Т'],
  KeyM: ['m', 'ь', 'M', 'Ь'],
  Comma: [',', 'б', '<', 'Б'],
  Period: ['.', 'ю', '>', 'Ю'],
  Slash: ['/', '.', '?', ','],
};
